model_type: "cl"
train_size: 0.6
val_size: 0.2
embedding_size: 16
hidden_size: 512
composite_transforms_size: 7
use_pre_paired_dataset: true
in_channels: 6 # number of node features for gnn input
out_channels: 16 # should be equal to embedding_size
pooling_strategy: "global_avg"
epochs: 2500
ema_alpha: 0.05
restore_best: true
shuffle: true
  