learning_rate:
  range: [0.00001, 0.1]
  tune: true
  type: loguniform
  default: 1e-3
n_layers:
  range: [2, 10]
  tune: true
  type: int
  default: 5
batch_size:
  choices: [4, 8, 12]
  tune: true
  type: categorical
  default: 11
patience:
  range: [0, 1000]
  tune: false
  type: int
  default: None # None means no early stopping
projection_size:
  range: [4, 16]
  tune: true
  type: int
  default: 12
temperature:
  range: [0.01, 1.0]
  tune: true
  type: loguniform
  default: 0.1
epochs:
  range: [100, 300]
  tune: true
  type: int
  default: 2500


