learning_rate:
  range: [0.00001, 0.1]
  tune: true
  type: loguniform
  default: 1e-3
n_layers:
  range: [2, 10]
  tune: true
  type: int
  default: 5
batch_size:
  choices: [4, 8, 16, 32]
  tune: true
  type: categorical
  default: 11
patience:
  range: [0, 1000]
  tune: false
  type: int
  default: None # None means no early stopping
projection_size:
  range: [8, 512]
  tune: true
  type: int
  default: 12
tau: # temperature parameter for contrastive loss in SimCLR, target decay rate in BYOL
  range: [0.01, 1.0]
  tune: true
  type: loguniform
  default: 0.996
epochs:
  range: [2, 3]
  tune: true
  type: int
  default: 2


